version: '2'

services:
  mysql:
    image: mysql:5.7
    restart: always
    ports:
      - 3306
    environment:
      - MYSQL_ROOT_PASSWORD=helper
      - MYSQL_DATABASE=helperbase
      - MYSQL_USER=pb
      - MYSQL_PASSWORD=pbpass
    volumes:
      - ./db/data:/var/lib/mysql
  nginx:
    image: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - .:/app
      - ./docker/nginx/sites/local.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/local.default.conf:/etc/nginx/local.default.conf
    links:
      - php-fpm

  php-fpm:
    extends:
      file: docker/php/php.yml
      service: php
    restart: always
    working_dir: /app
    volumes:
      - .:/app
    links:
      - mysql
